[workspace]
resolver = "2"
members = [".", "napi"]

[package]
edition = "2021"
name = "datalayer-driver"
version = "0.1.46"
license = "MIT"
authors = ["yakuhito <y@kuhi.to>"]
homepage = "https://github.com/DIG-Network/DataLayer-Driver"
repository = "https://github.com/DIG-Network/DataLayer-Driver"
description = "Native Chia DataLayer Driver for storing and retrieving data in Chia blockchain"
readme = "README.md"
keywords = ["chia", "blockchain", "datalayer", "storage", "web3"]
categories = ["cryptography::cryptocurrencies", "web-programming"]

[dependencies]
chia = "0.22.0"
chia-puzzles = "0.20.1"
thiserror = "1.0.61"
clvmr = "0.13.1"
tokio = "1.39.3"
chia-wallet-sdk = { version = "0.24.0", features = ["chip-0035", "native-tls", "peer-simulator"] }
hex-literal = "0.4.1"
num-bigint = "0.4.6"
hex = "0.4.3"
rand = "0.8"
futures-util = "0.3"

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.x86_64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = { version = "0.9.102", features = ["vendored"] }

[profile.release]
lto = true
strip = "symbols"