[package]
name = "datalayer_driver"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["yakuhito <y@kuhi.to>"]
homepage = "https://github.com/Datalayer-Storage/DataLayer-Driver"
repository = "https://github.com/Datalayer-Storage/DataLayer-Driver"

[dependencies]
chia = "0.9.0"
hex-literal = "0.4.1"
chia-protocol = "0.9.0"
chia-puzzles = "0.9.0"
clvm-traits = "0.9.0"
clvm-utils = "0.9.0"
clvm-derive = "0.9.0"
clvmr = "0.7.0"
chia-sdk-driver = "0.10.3"
chia-sdk-test = "0.10.3"
tokio = "1.38.0"
anyhow = "1.0.86"
